// core/src/api/auth.rs
// Pillar 1 authentication for dev/test:
//   - register/login via username + password (Argon2id)
//   - request identity via `x-user-id` header (no JWT)

use argon2::{
    password_hash::{rand_core::OsRng, PasswordHash, PasswordHasher, PasswordVerifier, SaltString},
    Argon2,
};
use axum::{
    async_trait,
    extract::{FromRequestParts, State},
    http::{request::Parts, StatusCode},
    Json,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::api::state::AppState;

// ─────────────────────────────────────────────────────────────────────────────
// Public type
// ─────────────────────────────────────────────────────────────────────────────

/// The authenticated caller's user ID, extracted from the `x-user-id` header.
///
/// Usage — add as a handler parameter:
/// ```rust,ignore
/// async fn my_handler(UserId(uid): UserId, ...) { /* ... */ }
/// ```
/// Axum will reject the request with 401/400 if the header is absent or invalid.
#[derive(Debug, Clone, Copy)]
pub struct UserId(pub u64);

#[derive(Deserialize)]
pub struct RegisterRequest {
    pub username: String,
    pub password: String,
}

#[derive(Deserialize)]
pub struct LoginRequest {
    pub username: String,
    pub password: String,
}

#[derive(Serialize)]
pub struct AuthResponse {
    pub user_id: String,
    pub username: String,
    pub auth_mode: String,
    pub auth_header: String,
}

#[derive(Serialize)]
pub struct UserListItem {
    pub user_id: String,
    pub username: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Extractor implementation
// ─────────────────────────────────────────────────────────────────────────────

#[async_trait]
impl<S> FromRequestParts<S> for UserId
where
    S: Send + Sync,
{
    type Rejection = (StatusCode, Json<Value>);

    async fn from_request_parts(parts: &mut Parts, _state: &S) -> Result<Self, Self::Rejection> {
        // 1. Header must be present.
        let header_val = parts
            .headers
            .get("x-user-id")
            .ok_or_else(|| err(StatusCode::UNAUTHORIZED, "missing x-user-id header"))?;

        // 2. Header value must be valid ASCII/UTF-8.
        let str_val = header_val
            .to_str()
            .map_err(|_| err(StatusCode::BAD_REQUEST, "x-user-id must be valid ASCII"))?;

        // 3. Value must parse as a non-zero u64.
        let user_id = str_val
            .parse::<u64>()
            .map_err(|_| err(StatusCode::BAD_REQUEST, "x-user-id must be a positive integer (u64)"))?;

        if user_id == 0 {
            return Err(err(StatusCode::BAD_REQUEST, "x-user-id must be greater than 0"));
        }

        Ok(UserId(user_id))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Auth handlers
// ─────────────────────────────────────────────────────────────────────────────

type ApiError = (StatusCode, Json<Value>);

const MAX_JS_SAFE_INTEGER_I64: i64 = 9_007_199_254_740_991;

/// POST /api/auth/register
///
/// Creates a new user with Argon2id-hashed password and initializes zero
/// balances for all assets found in `assets`.
pub async fn register_handler(
    State(state): State<AppState>,
    Json(body): Json<RegisterRequest>,
) -> Result<(StatusCode, Json<AuthResponse>), ApiError> {
    let username = normalize_username(&body.username)?;
    validate_password(&body.password)?;
    let password_hash = hash_password(&body.password)?;

    let mut tx = state.db.begin().await.map_err(db_err)?;

    // Serialize user ID allocation in dev/test mode to avoid race conditions
    // with BIGINT IDs generated by application logic.
    sqlx::query("SELECT pg_advisory_xact_lock($1)")
        .bind(92_011_i64)
        .execute(&mut *tx)
        .await
        .map_err(db_err)?;

    let (next_id,): (i64,) = sqlx::query_as(
        "SELECT COALESCE(MAX(id), 0) + 1
         FROM users
         WHERE id > 0 AND id <= $1",
    )
        .bind(MAX_JS_SAFE_INTEGER_I64)
        .fetch_one(&mut *tx)
        .await
        .map_err(db_err)?;

    if next_id <= 0 || next_id > MAX_JS_SAFE_INTEGER_I64 {
        return Err(internal("generated invalid user id"));
    }

    let inserted = sqlx::query(
        "INSERT INTO users (id, username, password_hash)
         VALUES ($1, $2, $3)
         ON CONFLICT (username) DO NOTHING",
    )
    .bind(next_id)
    .bind(&username)
    .bind(&password_hash)
    .execute(&mut *tx)
    .await
    .map_err(db_err)?;

    if inserted.rows_affected() == 0 {
        return Err(conflict("username already exists"));
    }

    sqlx::query(
        "INSERT INTO balances (user_id, asset_symbol, available, locked)
         SELECT $1, symbol, 0, 0 FROM assets
         ON CONFLICT (user_id, asset_symbol) DO NOTHING",
    )
    .bind(next_id)
    .execute(&mut *tx)
    .await
    .map_err(db_err)?;

    tx.commit().await.map_err(db_err)?;

    let user_id = u64::try_from(next_id).map_err(|_| internal("user id overflow"))?;
    Ok((
        StatusCode::CREATED,
        Json(auth_response(user_id, username)),
    ))
}

/// POST /api/auth/login
///
/// Verifies username/password with Argon2id and returns user identity metadata.
/// Clients must send `x-user-id` in subsequent authenticated requests.
pub async fn login_handler(
    State(state): State<AppState>,
    Json(body): Json<LoginRequest>,
) -> Result<Json<AuthResponse>, ApiError> {
    let username = normalize_username(&body.username)?;
    validate_password(&body.password)?;

    let row: Option<(i64, String, Option<String>)> = sqlx::query_as(
        "SELECT id, username, password_hash
         FROM users
         WHERE username = $1",
    )
    .bind(&username)
    .fetch_optional(&state.db)
    .await
    .map_err(db_err)?;

    let (id, db_username, password_hash) = row.ok_or_else(|| unauthorized("invalid username or password"))?;
    let stored_hash = password_hash.ok_or_else(|| unauthorized("invalid username or password"))?;

    verify_password(&body.password, &stored_hash)?;

    let user_id = u64::try_from(id).map_err(|_| internal("invalid user id in database"))?;
    Ok(Json(auth_response(user_id, db_username)))
}

/// GET /api/auth/me
///
/// Uses `x-user-id` extraction and returns the associated username.
pub async fn me_handler(
    State(state): State<AppState>,
    UserId(user_id): UserId,
) -> Result<Json<AuthResponse>, ApiError> {
    let row: Option<(String,)> = sqlx::query_as("SELECT username FROM users WHERE id = $1")
        .bind(user_id as i64)
        .fetch_optional(&state.db)
        .await
        .map_err(db_err)?;

    let (username,) = row.ok_or_else(|| unauthorized("invalid x-user-id"))?;
    Ok(Json(auth_response(user_id, username)))
}

/// GET /api/auth/users
///
/// Returns all users in the database for admin/testing selectors.
pub async fn users_handler(
    State(state): State<AppState>,
    UserId(_caller_id): UserId,
) -> Result<Json<Vec<UserListItem>>, ApiError> {
    let rows: Vec<(i64, String)> = sqlx::query_as(
        "SELECT id, username
         FROM users
         WHERE id > 0
         ORDER BY id ASC",
    )
    .fetch_all(&state.db)
    .await
    .map_err(db_err)?;

    let users = rows
        .into_iter()
        .filter_map(|(id, username)| {
            u64::try_from(id).ok().map(|uid| UserListItem {
                user_id: uid.to_string(),
                username,
            })
        })
        .collect();

    Ok(Json(users))
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper
// ─────────────────────────────────────────────────────────────────────────────

#[inline]
fn err(status: StatusCode, message: &str) -> (StatusCode, Json<Value>) {
    (status, Json(json!({ "error": message })))
}

#[inline]
fn db_err(e: sqlx::Error) -> ApiError {
    err(StatusCode::INTERNAL_SERVER_ERROR, &format!("database error: {e}"))
}

#[inline]
fn conflict(message: &str) -> ApiError {
    err(StatusCode::CONFLICT, message)
}

#[inline]
fn unauthorized(message: &str) -> ApiError {
    err(StatusCode::UNAUTHORIZED, message)
}

#[inline]
fn internal(message: &str) -> ApiError {
    err(StatusCode::INTERNAL_SERVER_ERROR, message)
}

fn normalize_username(raw: &str) -> Result<String, ApiError> {
    let username = raw.trim().to_lowercase();
    if username.len() < 3 || username.len() > 32 {
        return Err(err(
            StatusCode::BAD_REQUEST,
            "username length must be between 3 and 32 characters",
        ));
    }
    if !username
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
    {
        return Err(err(
            StatusCode::BAD_REQUEST,
            "username may only contain [a-z0-9_-]",
        ));
    }
    Ok(username)
}

fn validate_password(password: &str) -> Result<(), ApiError> {
    if password.len() < 8 || password.len() > 128 {
        return Err(err(
            StatusCode::BAD_REQUEST,
            "password length must be between 8 and 128 characters",
        ));
    }
    Ok(())
}

fn hash_password(password: &str) -> Result<String, ApiError> {
    let salt = SaltString::generate(&mut OsRng);
    let hash = Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map_err(|_| internal("failed to hash password"))?
        .to_string();
    Ok(hash)
}

fn verify_password(password: &str, password_hash: &str) -> Result<(), ApiError> {
    let parsed = PasswordHash::new(password_hash)
        .map_err(|_| unauthorized("invalid username or password"))?;

    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .map_err(|_| unauthorized("invalid username or password"))
}

fn auth_response(user_id: u64, username: String) -> AuthResponse {
    AuthResponse {
        user_id: user_id.to_string(),
        username,
        auth_mode: "x-user-id".to_string(),
        auth_header: format!("x-user-id: {user_id}"),
    }
}
